export const HEROES = [
  {
    id: 1,
    name: 'Superman',
    strength: 100,
    power: 100,
    velocity: 100,
    mortality: false,
    image: 'https://example.com/superman.jpg',
  },
  {
    id: 2,
    name: 'Batman',
    strength: 80,
    power: 70,
    velocity: 60,
    mortality: true,
    image: 'https://example.com/batman.jpg',
  },
  {
    id: 3,
    name: 'Wonder Woman',
    strength: 100,
    power: 100,
    velocity: 100,
    mortality: false,
    image: 'https://example.com/wonderwoman.jpg',
  },
  {
    id: 4,
    name: 'Flash',
    strength: 70,
    power: 80,
    velocity: 100,
    mortality: true,
    image: 'https://example.com/flash.jpg',
  },
  {
    id: 5,
    name: 'Green Lantern',
    strength: 90,
    power: 90,
    velocity: 80,
    mortality: false,
    image: 'https://example.com/greenlantern.jpg',
  },
  {
    id: 6,
    name: 'Aquaman',
    strength: 85,
    power: 75,
    velocity: 70,
    mortality: true,
    image: 'https://example.com/aquaman.jpg',
  },
  {
    id: 7,
    name: 'Cyborg',
    strength: 80,
    power: 85,
    velocity: 75,
    mortality: false,
    image: 'https://example.com/cyborg.jpg',
  },
  {
    id: 8,
    name: 'Green Arrow',
    strength: 75,
    power: 70,
    velocity: 80,
    mortality: true,
    image: 'https://example.com/greenarrow.jpg',
  },
];
