import { Hero } from '../interfaces/hero';

export const HEROES_MOCK: Hero[] = [
  {
    id: 1,
    name: 'Superman',
    alias: 'Man of steel',
    powers: ['Super strength'],
    firstAppearance: '1938',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Kal-El',
    origin: 'Krypton',
    imageUrl: 'img/superman.jpg',
  },
  {
    id: 2,
    name: 'Batman',
    alias: 'The Dark Night',
    powers: ['Intelligence'],
    firstAppearance: '1939',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Bruce Wayne',
    origin: 'Gotham City',
    imageUrl: 'img/batman.jpg',
  },
  {
    id: 3,
    name: 'Wonder Woman',
    alias: 'Amazonian Princess',
    powers: ['Super strength', 'Flight'],
    firstAppearance: '1941',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Diana Prince',
    origin: 'Themyscira',
    imageUrl: 'img/wonderwoman.jpg',
  },
  {
    id: 4,
    name: 'Flash',
    alias: 'Scarlet Speedster',
    powers: ['Super speed'],
    firstAppearance: '1940',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Barry Allen',
    origin: 'Central City',
    imageUrl: 'img/flash.jpg',
  },
  {
    id: 5,
    name: 'Green Lantern',
    alias: 'Emerald Knight',
    powers: ['Power ring'],
    firstAppearance: '1940',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Hal Jordan',
    origin: 'Earth',
    imageUrl: 'img/greenlantern.jpg',
  },
  {
    id: 6,
    name: 'Aquaman',
    alias: 'King of Atlantis',
    powers: ['Super strength', 'Aquatic abilities'],
    firstAppearance: '1941',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Arthur Curry',
    origin: 'Atlantis',
    imageUrl: 'img/aquaman.jpg',
  },
  {
    id: 7,
    name: 'Cyborg',
    alias: 'Half Human, Half Machine',
    powers: ['Technopathy', 'Super strength'],
    firstAppearance: '1980',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Victor Stone',
    origin: 'Earth',
    imageUrl: 'img/cyborg.jpg',
  },
  {
    id: 8,
    name: 'Green Arrow',
    alias: 'Emerald Archer',
    powers: ['Archery', 'Hand-to-hand combat'],
    firstAppearance: '1941',
    alignment: 'Good',
    team: 'Justice League',
    realName: 'Oliver Queen',
    origin: 'Star City',
    imageUrl: 'img/greenarrow.jpg',
  },
];
